name: Prueba tokens

on: push

jobs:
  comparar:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: powershell
        env:
          SECRET_DEV: ${{ secrets.DEV_TOKEN }}
        run: |
          if ($env:SECRET_DEV -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "Los tokens COINCIDEN"
          } else {
            Write-Host "Los tokens NO coinciden"
          }
